import type { Metadata } from "next";
import EmployeeTemplate from "@/components/employe template";

export const metadata: Metadata = {
  title: "Acces by KAI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <EmployeeTemplate>{children}</EmployeeTemplate>
  );
}